import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,ArchiveRestore,BarChart3,Building2,Camera,CheckCircle2,ChevronRight,Edit3,ExternalLink,FileText,Gauge,Globe2,Image,LayoutDashboard,Lock,LogOut,MessageSquare,MonitorSmartphone,Palette,RefreshCw,Save,Search,Settings,ShieldCheck,Sparkles,Star,Trash2,Undo2,Upload,Users,Zap}from'lucide-react';
import{websiteSections,initialRows}from'./data/websiteDefaults.js';
import{supabase,isSupabaseConfigured,siteUrl}from'./lib/supabase.js';
import'./styles.css';

const nav=[['dashboard','Dashboard',LayoutDashboard],['website','Website Fields',Edit3],['services','Services',Building2],['projects','Projects',Image],['sectors','Sectors',Globe2],['news','News & Insights',FileText],['team','Team',Users],['testimonials','Testimonials',Star],['media_assets','Media Library',Camera],['enquiries','Enquiries',MessageSquare],['trash','Restore Center',ArchiveRestore],['seo','SEO & Speed',Gauge],['settings','Settings',Settings]];
const tables=['site_sections','services','projects','sectors','news','team','testimonials','media_assets','enquiries'];
function key(table){return 'doma_admin_'+table}
function readLocal(table,fallback=[]){try{return JSON.parse(localStorage.getItem(key(table)))||fallback}catch{return fallback}}
function writeLocal(table,value){localStorage.setItem(key(table),JSON.stringify(value))}
function stamp(row){return{...row,updated_at:new Date().toISOString(),created_at:row.created_at||new Date().toISOString()}}
async function listRows(table,{includeDeleted=false}={}){if(!supabase){let data=readLocal(table,table==='site_sections'?websiteSections:initialRows[table]||[]).map(stamp);return includeDeleted?data:data.filter(x=>!x.deleted_at)}let q=supabase.from(table).select('*').order('updated_at',{ascending:false});if(!includeDeleted)q=q.is('deleted_at',null);let{data,error}=await q;if(error)throw error;return data||[]}
async function upsertRow(table,row){let item=stamp({...row,id:row.id||crypto.randomUUID(),deleted_at:row.deleted_at ?? null});if(!supabase){let arr=readLocal(table,table==='site_sections'?websiteSections:initialRows[table]||[]);let next=arr.some(x=>(x.id&&x.id===item.id)||(x.section_key&&x.section_key===item.section_key))?arr.map(x=>((x.id&&x.id===item.id)||(x.section_key&&x.section_key===item.section_key))?item:x):[item,...arr];writeLocal(table,next);return item}let{data,error}=await supabase.from(table).upsert(item).select().single();if(error)throw error;await logAction('UPSERT',table,data?.id);return data}
async function softDelete(table,row){let item=stamp({...row,deleted_at:new Date().toISOString()});return upsertRow(table,item)}
async function restoreRow(table,row){let item=stamp({...row,deleted_at:null});return upsertRow(table,item)}
async function logAction(action,table,record){try{if(!supabase)return;await supabase.from('audit_logs').insert({action,table_name:table,record_id:record})}catch{}}
function safe(v){return v===null||v===undefined?'':String(v)}

async function optimiseImageFile(file,{maxWidth=1600,maxHeight=1200,quality=0.86}={}){if(!file?.type?.startsWith('image/'))return file;const bitmap=await createImageBitmap(file);let{width,height}=bitmap;const ratio=Math.min(maxWidth/width,maxHeight/height,1);const targetWidth=Math.round(width*ratio),targetHeight=Math.round(height*ratio);const canvas=document.createElement('canvas');canvas.width=targetWidth;canvas.height=targetHeight;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(bitmap,0,0,targetWidth,targetHeight);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',quality));if(!blob)throw new Error('Image optimisation failed. Please try another image.');const cleanName=file.name.replace(/\.[^.]+$/,'').replace(/[^a-z0-9-_]+/gi,'-').toLowerCase();return new File([blob],`${cleanName || 'doma-image'}.webp`,{type:'image/webp'});}

function App(){const[session,setSession]=useState(null),[checking,setChecking]=useState(true);useEffect(()=>{if(!supabase){setChecking(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);if(checking)return <Splash/>;if(isSupabaseConfigured&&!session)return <Login/>;return <Shell/>}
function Splash(){return <div className="splash"><Sparkles/><h2>Loading DOMA Admin</h2></div>}
function Login(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState(''),[loading,setLoading]=useState(false);async function submit(e){e.preventDefault();setLoading(true);setErr('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setErr(error.message);setLoading(false)}return <div className="login"><form onSubmit={submit} className="loginCard"><div className="logoMark"><Building2/></div><h1>DOMA Secure Admin</h1><p>Production login through Supabase Auth. No password is stored inside the frontend code.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="admin@domabuild.co.uk"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required placeholder="••••••••"/></label>{err&&<div className="alert bad">{err}</div>}<button disabled={loading}>{loading?'Checking...':'Secure Login'}</button></form></div>}
function Shell(){const[page,setPage]=useState('dashboard');return <div className="app"><aside><div className="brand"><div className="brandIcon"><Building2/></div><div><b>DOMA</b><span>Website Admin</span></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setPage(id)} className={page===id?'active':''}><Icon size={18}/>{label}</button>)}</nav><a className="visit" href={siteUrl} target="_blank"><ExternalLink size={17}/>Open DOMA Website</a><button className="logout" onClick={()=>supabase?.auth.signOut()}><LogOut size={17}/>Logout</button></aside><main><Topbar page={page}/><Router page={page} setPage={setPage}/></main></div>}
function Topbar({page}){return <div className="topbar"><div><p>DOMA Build Contractors Ltd</p><h1>{nav.find(n=>n[0]===page)?.[1]||'Dashboard'}</h1></div><div className="topActions"><span className="pill"><CheckCircle2 size={16}/>Fast updates</span><span className="pill"><ShieldCheck size={16}/>RLS secure</span><a href={siteUrl} target="_blank">Live Preview <ExternalLink size={15}/></a></div></div>}
function Router({page,setPage}){if(page==='dashboard')return <Dashboard setPage={setPage}/>;if(page==='website')return <WebsiteFields/>;if(page==='services')return <Crud title="Services" table="services" fields={['title','description','icon','sort_order','is_active']}/>;if(page==='projects')return <Crud title="Projects" table="projects" fields={['title','category','location','status','description','image_url','is_featured','is_active']}/>;if(page==='sectors')return <Crud title="Sectors" table="sectors" fields={['title','description','sort_order','is_active']}/>;if(page==='news')return <Crud title="News & Insights" table="news" fields={['title','slug','excerpt','content','image_url','is_active']}/>;if(page==='team')return <Crud title="Team" table="team" fields={['name','role','bio','photo_url','is_active']}/>;if(page==='testimonials')return <Crud title="Testimonials" table="testimonials" fields={['client_name','client_role','quote','rating','is_active']}/>;if(page==='media_assets')return <Media/>;if(page==='enquiries')return <Crud title="Enquiries" table="enquiries" fields={['name','email','phone','service','message','status','follow_up_date','notes']}/>;if(page==='trash')return <TrashCenter/>;if(page==='seo')return <SeoSpeed/>;return <SettingsPage/>}
function Dashboard({setPage}){const[stats,setStats]=useState({projects:0,services:0,enquiries:0,sections:0});useEffect(()=>{Promise.all([listRows('projects'),listRows('services'),listRows('enquiries'),listRows('site_sections')]).then(([p,s,e,sec])=>setStats({projects:p.length,services:s.length,enquiries:e.length,sections:sec.length})).catch(()=>{})},[]);return <><div className="heroPanel"><div><span className="eyebrow"><Zap/>Live website control</span><h2>Professional admin dashboard for DOMA Build website content.</h2><p>Clean construction-business CMS for pages, services, projects, sectors, team, gallery, enquiries, SEO, footer and website settings.</p><div className="actions"><button onClick={()=>setPage('website')}>Edit Website Fields <ChevronRight size={18}/></button><button className="ghost" onClick={()=>setPage('seo')}>Speed Settings</button></div></div><LivePreview/></div><div className="cards"><Stat icon={Image} label="Projects" value={stats.projects}/><Stat icon={Building2} label="Services" value={stats.services}/><Stat icon={MessageSquare} label="Enquiries" value={stats.enquiries}/><Stat icon={FileText} label="Editable Sections" value={stats.sections||websiteSections.length}/></div><div className="grid2"><Panel title="Quick Update Workflow"><Steps/></Panel><Panel title="Speed & Live Sync Strategy"><ul><li>Website reads published content only.</li><li>Admin soft-delete protects accidental deletion.</li><li>Images are compressed and cached.</li><li>Supabase Free is used only for CMS data and small media.</li><li>Existing DOMA site remains safe until the supplied integration client is added.</li></ul></Panel></div></>}
function LivePreview(){return <div className="previewCard"><div className="browser"><span/><span/><span/><b>domabuild.co.uk</b></div><div className="siteShot"><h3>CONSTRUCTION<br/>BUILT ON TRUST</h3><p>Professional construction website preview</p></div></div>}
function Stat({icon:Icon,label,value}){return <div className="card"><Icon/><span>{label}</span><b>{value}</b></div>}
function Steps(){return <div className="steps"><div><Edit3/>Edit in Admin</div><ChevronRight/><div><Save/>Save</div><ChevronRight/><div><Zap/>Sync</div><ChevronRight/><div><Globe2/>Website Live</div></div>}
function WebsiteFields(){const[sections,setSections]=useState([]),[selected,setSelected]=useState(null),[msg,setMsg]=useState('');useEffect(()=>{load()},[]);async function load(){let rows=await listRows('site_sections');if(!rows.length){rows=websiteSections.map((s,i)=>({...s,sort_order:i+1,id:crypto.randomUUID()}));for(const r of rows)await upsertRow('site_sections',r)}setSections(rows);setSelected(rows[0]||null)}async function save(){await upsertRow('site_sections',selected);setMsg('Saved. Website can fetch this section instantly from Supabase.');load()}function updateField(k,v){setSelected({...selected,fields:{...(selected.fields||{}),[k]:v}})}if(!selected)return <Panel title="Website Fields"><button onClick={load}>Load website fields</button></Panel>;return <div className="builder"><div className="sectionList"><h3>Website Sections</h3>{sections.map(s=><button key={s.section_key} onClick={()=>setSelected(s)} className={selected.section_key===s.section_key?'active':''}>{s.title}</button>)}</div><div className="editor"><div className="editorHead"><div><h2>{selected.title}</h2><p>Update fields mapped to DOMA website section: <b>{selected.section_key}</b></p></div><button onClick={save}><Save size={17}/>Save Section</button></div><div className="formGrid">{Object.entries(selected.fields||{}).map(([k,v])=><label key={k}><span>{k.replaceAll('_',' ')}</span>{safe(v).length>70?<textarea value={safe(v)} onChange={e=>updateField(k,e.target.value)}/>:<input value={safe(v)} onChange={e=>updateField(k,e.target.value)}/>}</label>)}</div>{msg&&<div className="alert good">{msg}</div>}</div></div>}
function Crud({title,table,fields}){const[rows,setRows]=useState([]),[form,setForm]=useState({}),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true),[err,setErr]=useState('');useEffect(()=>{load()},[table]);async function load(){setLoading(true);setErr('');try{let data=await listRows(table);if(!data.length&&(initialRows[table]||[]).length){data=initialRows[table].map(x=>stamp({...x,id:crypto.randomUUID()}));for(const r of data)await upsertRow(table,r)}setRows(data)}catch(e){setErr(e.message)}setLoading(false)}function change(k,v){setForm({...form,[k]:v})}async function save(e){e.preventDefault();await upsertRow(table,{...form,id:editing});setForm({});setEditing(null);load()}async function del(row){if(confirm('Move this item to Restore Center? You can restore it later.')){await softDelete(table,row);load()}}return <Panel title={title}><div className="moduleNote"><CheckCircle2 size={17}/>Content shown here is production CMS data, not dummy CRM text. Deleted records go to Restore Center.</div><form onSubmit={save} className="proForm">{fields.map(f=><label key={f}><span>{f.replaceAll('_',' ')}</span>{f.includes('description')||f==='content'||f==='message'||f==='notes'||f==='quote'?<textarea value={safe(form[f])} onChange={e=>change(f,e.target.value)}/>:f.startsWith('is_')?<select value={String(form[f]??true)} onChange={e=>change(f,e.target.value==='true')}><option value="true">Yes</option><option value="false">No</option></select>:<input value={safe(form[f])} onChange={e=>change(f,e.target.value)}/>}</label>)}<button><Save size={16}/>{editing?'Update':'Add'} {title}</button>{editing&&<button type="button" className="ghost" onClick={()=>{setEditing(null);setForm({})}}>Cancel</button>}</form>{err&&<div className="alert bad">{err}</div>}{loading?<div className="skeleton">Loading {title}...</div>:<DataTable rows={rows} fields={fields} onEdit={r=>{setEditing(r.id);setForm(r);scrollTo({top:0,behavior:'smooth'})}} onDelete={del}/>}</Panel>}
function DataTable({rows,fields,onEdit,onDelete}){if(!rows.length)return <div className="empty">No records yet. Add first record above.</div>;return <div className="table"><table><thead><tr>{fields.slice(0,4).map(f=><th key={f}>{f.replaceAll('_',' ')}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{fields.slice(0,4).map(f=><td key={f}>{safe(r[f]).slice(0,90)}</td>)}<td><button onClick={()=>onEdit(r)}>Edit</button><button className="danger" onClick={()=>onDelete(r)}><Trash2 size={15}/>Delete</button></td></tr>)}</tbody></table></div>}
function Media(){const[file,setFile]=useState(null),[msg,setMsg]=useState(''),[url,setUrl]=useState(''),[uploading,setUploading]=useState(false);async function upload(){try{if(!file){setMsg('Select an image or PDF first.');return}setUploading(true);setMsg('Preparing file...');let uploadFile=file;if(file.type.startsWith('image/')){uploadFile=await optimiseImageFile(file,{maxWidth:1800,maxHeight:1400,quality:0.88});if(uploadFile.size>1.5*1024*1024)uploadFile=await optimiseImageFile(file,{maxWidth:1400,maxHeight:1000,quality:0.78})}if(uploadFile.size>3*1024*1024){setMsg('File is still too large. Please use an image/PDF below 3 MB.');return}if(!supabase){setMsg('Production storage is not connected yet. After Supabase env setup, upload will work directly from this page.');return}const safeName=uploadFile.name.replace(/[^a-z0-9._-]+/gi,'-').toLowerCase();const path=`doma/${Date.now()}-${safeName}`;const{error}=await supabase.storage.from('doma-media').upload(path,uploadFile,{cacheControl:'31536000',upsert:false,contentType:uploadFile.type});if(error)throw error;const{data}=supabase.storage.from('doma-media').getPublicUrl(path);setUrl(data.publicUrl);await upsertRow('media_assets',{title:file.name,file_url:data.publicUrl,file_type:uploadFile.type,size_bytes:uploadFile.size,alt_text:file.name.replace(/\.[^.]+$/,''),is_active:true});setMsg(`Uploaded successfully. Optimised size: ${(uploadFile.size/1024).toFixed(0)} KB`)}catch(e){setMsg(e.message||'Upload failed. Please try again.')}finally{setUploading(false)}}return <Panel title="Media Library"><p>Upload images safely. The admin automatically resizes large images, converts them to WebP quality format, and stores the final URL in Media Library.</p><div className="uploadBox"><input type="file" accept="image/*,.pdf" onChange={e=>{setFile(e.target.files[0]);setMsg('')}}/><button type="button" disabled={uploading} onClick={upload}><Upload size={16}/>{uploading?'Uploading...':'Optimise & Upload'}</button></div>{file&&<div className="moduleNote"><Image size={17}/>Selected: {file.name} • {(file.size/1024).toFixed(0)} KB</div>}{msg&&<div className={msg.includes('successfully')?'alert good':'alert'}>{msg}</div>}{url&&<input readOnly value={url}/>}<Crud title="Saved Media Assets" table="media_assets" fields={['title','file_url','file_type','alt_text','is_active']}/></Panel>}
function TrashCenter(){const[items,setItems]=useState([]),[loading,setLoading]=useState(false);async function load(){setLoading(true);let all=[];for(const t of tables){try{const rows=await listRows(t,{includeDeleted:true});all.push(...rows.filter(r=>r.deleted_at).map(r=>({...r,_table:t})))}catch{}}setItems(all);setLoading(false)}useEffect(()=>{load()},[]);async function restore(item){await restoreRow(item._table,item);load()}return <Panel title="Restore Center"><p>Accidentally deleted website content is not permanently removed. Restore it from here.</p><button onClick={load}><RefreshCw size={16}/>Refresh</button>{loading?<div className="skeleton">Checking deleted records...</div>:!items.length?<div className="empty">No deleted records found.</div>:<div className="table"><table><thead><tr><th>Module</th><th>Name / Title</th><th>Deleted At</th><th>Action</th></tr></thead><tbody>{items.map((r,i)=><tr key={r.id||i}><td>{r._table}</td><td>{r.title||r.name||r.client_name||r.section_key||r.email}</td><td>{new Date(r.deleted_at).toLocaleString()}</td><td><button onClick={()=>restore(r)}><Undo2 size={15}/>Restore</button></td></tr>)}</tbody></table></div>}</Panel>}
function SeoSpeed(){return <div className="grid2"><Panel title="SEO Manager"><p>Update SEO from Website Fields → Default SEO. Use page-specific SEO in News/Projects when required.</p><div className="mini"><span>Meta Title</span><span>Meta Description</span><span>OG Image</span><span>Canonical URL</span><span>Schema</span><span>Sitemap</span></div></Panel><Panel title="No Loading Issue Setup"><ul><li>Build website as static pages and fetch minimal JSON from Supabase.</li><li>Use local cache fallback in frontend.</li><li>Set WebP images, lazy loading and CDN cache.</li><li>Do not query all tables on public website; fetch only required section.</li><li>Keep admin and public website separated for security.</li></ul><div className="score"><Gauge/><b>Target PageSpeed: 90+</b></div></Panel></div>}
function SettingsPage(){return <div className="settingsPage"><div className="settingsHeader"><h2>Website Settings</h2><p>Manage live website configuration without showing development or demo messages.</p></div><section className="settingsCard"><label><span>Website URL</span><input value={siteUrl} readOnly/></label><div className="settingsRow"><div><b>Preview Mode</b><p>Review content changes before publishing them on the live website.</p></div><label className="switch"><input type="checkbox"/><span></span></label></div><div className="settingsRow"><div><b>Environment</b><p>Production-ready admin interface for DOMA Build website updates.</p></div><span className="statusBadge">Production</span></div><div className="settingsRow"><div><b>Media Quality</b><p>Image uploads are resized, converted to WebP and saved with CDN cache.</p></div><span className="statusBadge gold">Optimised</span></div><button className="saveSettings"><Save size={16}/>Save Changes</button></section></div>}
function Panel({title,children}){return <section className="panel"><h2>{title}</h2>{children}</section>}
createRoot(document.getElementById('root')).render(<App/>);
